from .primitives import *

SYMBOL_PRIMITIVES = [
    ArithmeticPrimitives,
    IterationPrimitives,
    ValueHandlingPrimitives,
    StringHelperPrimitives,
    CastingPrimitives,
    ComparisonPrimitives,
    ExpressionHandlingPrimitives,
    DataHandlingPrimitives,
    UniquenessPrimitives,
    PatternMatchingPrimitives,
    DictHandlingPrimitives,
    QueryHandlingPrimitives,
    ExecutionControlPrimitives,
    TemplateStylingPrimitives,
    DataClusteringPrimitives,
    EmbeddingPrimitives,
    IndexingPrimitives,
    IOHandlingPrimitives,
    PersistencePrimitives,
    OutputHandlingPrimitives,
    FineTuningPrimitives,
]